version: 2
updates:
  - package-ecosystem: npm
    directory: /front-end
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /back-end
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /deployment
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /front-end
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /back-end
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
